import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";



export const metadata: Metadata = {
  title: "HBI Form",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;}>) {
    return (
      <html lang="pt-br">
        <body>
          <main>
            {children}
          
          </main>
        </body>
      </html>
    );
}

